public class Shuffle{
    public static void main(String[] args){
        int x = 3;
        while(x>0) {
            if (x>2){
                system.out.print("a");
            }
            x--;
            system.out.print("-");
            if (x == 2){
                system.out.print("b c");
            }
            
            if (x==1){
                system.out.print("d")
                x--;
            }
        }
    }
}